import sqlite3

conn = sqlite3.connect('Cars_new.db')
query = """CREATE TABLE CARS(NAME_OF_CAR CHAR(60) NOT NULL, NAME_OF_OWNER CHAR(100) NOT NULL)"""
conn.execute(query)
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('HYUNDAI','RAM')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('TOYOTA','SAM')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('DUSTER','PREM')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('SUZUKI','HARI')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('HONDA','NILA')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('HYUNDAI','DEV')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('BMW','KUMAR')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('WAGON','LILLY')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('HONDA','SAMMY')")
conn.execute("INSERT INTO CARS(NAME_OF_CAR,NAME_OF_OWNER)""VALUES('SUZUKI','KIRAN')")
conn.commit()
cursor = conn.execute("SELECT * from CARS")
print(cursor.fetchall())
conn.close()
